import Link from 'next/link';
import { redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';
import { addAttendanceTemplate,addDailyAttendanceSegment,applyTemplateToDate,applyTemplatesToMonth,deleteAttendanceTemplate,deleteDailyAttendanceSegment,duplicateAttendanceTemplate,updateAttendanceTemplate } from './actions';
import { updateDailyAttendanceSegment } from './edit-actions';

const WEEK=['一','二','三','四','五','六','日'];
const pad=(n:number)=>String(n).padStart(2,'0');
const nowParts=()=>{const d=new Date();return {date:`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`,month:`${d.getFullYear()}-${pad(d.getMonth()+1)}`}};

export default async function AttendanceSettingsPage({searchParams}:{searchParams:Promise<{date?:string;month?:string;message?:string;error?:string}>}){
  const q=await searchParams; const n=nowParts(); const selectedDate=q.date||n.date; const selectedMonth=q.month||selectedDate.slice(0,7)||n.month;
  const supabase=await createClient(); const {data:claims}=await supabase.auth.getClaims(); if(!claims?.claims?.sub)redirect('/login'); const {data:teamId}=await supabase.rpc('current_team_id'); if(!teamId)redirect('/more');
  const [{data:students},{data:templates},{data:segments}]=await Promise.all([
    supabase.from('students').select('id,display_name,grade,class_name,seat_number').eq('team_id',teamId).eq('active',true).order('grade').order('class_name').order('seat_number'),
    supabase.from('attendance_templates').select('id,weekday,mode,grade,student_id,start_time,end_time,default_count,note').eq('team_id',teamId).eq('active',true).order('weekday').order('start_time'),
    supabase.from('daily_attendance_segments').select('id,attendance_date,mode,grade,student_id,start_time,end_time,attendee_count,source,note').eq('team_id',teamId).eq('attendance_date',selectedDate).order('start_time'),
  ]);
  return <main className="shell">
    <section className="hero compactHero"><div className="eyebrow">ATTENDANCE ENGINE V2</div><h1>出勤／時段設定</h1><p>固定模板用表格式維護，可複製再改；整月一次套用後，只需要修改少數例外。</p><div className="topNav"><Link href="/today">今日訓練</Link><Link href="/aircon">冷氣費</Link><Link href="/payroll">教練薪酬</Link><Link href="/more">更多</Link></div></section>
    {q.message?<div className="notice successNotice">{q.message}</div>:null}{q.error?<div className="notice errorNotice">{q.error}</div>:null}

    <section className="card"><div className="sectionTitle"><div><span>01</span><h2>固定每週出席模板</h2></div><strong>表格式快速編輯</strong></div><div className="notice"><b>最快：</b>先建立一列，再按「複製」改星期、年級、人數或時間。</div>
      <form action={addAttendanceTemplate} className="gridForm"><label>星期<select name="weekday">{WEEK.map((w,i)=><option key={w} value={i+1}>星期{w}</option>)}</select></label><label>方式<select name="mode"><option value="grade">依年級</option><option value="individual">依個人</option></select></label><label>年級<select name="grade"><option value="">—</option>{[1,2,3,4,5,6].map(g=><option key={g} value={g}>{g}年級</option>)}</select></label><label>學生<select name="student_id"><option value="">—</option>{(students??[]).map(s=><option key={s.id} value={s.id}>{s.display_name}｜{s.grade??'-'}年{s.seat_number?` ${s.seat_number}號`:''}</option>)}</select></label><label>開始<input type="time" name="start_time" required/></label><label>結束<input type="time" name="end_time" required/></label><label>預設人數<input type="number" name="default_count" min="0"/></label><label>備註<input name="note"/></label><button className="primaryButton wide">＋ 新增一列</button></form>
      <div className="editableTableWrap">{(templates??[]).map(t=><article className="editRow" key={t.id}><form action={updateAttendanceTemplate} className="rowForm"><input type="hidden" name="id" value={t.id}/><select name="weekday" defaultValue={t.weekday}>{WEEK.map((w,i)=><option key={w} value={i+1}>週{w}</option>)}</select><select name="mode" defaultValue={t.mode}><option value="grade">年級</option><option value="individual">個人</option></select><select name="grade" defaultValue={t.grade??''}><option value="">—</option>{[1,2,3,4,5,6].map(g=><option key={g} value={g}>{g}年</option>)}</select><select name="student_id" defaultValue={t.student_id??''}><option value="">—</option>{(students??[]).map(s=><option key={s.id} value={s.id}>{s.display_name}</option>)}</select><input type="time" name="start_time" defaultValue={String(t.start_time).slice(0,5)} required/><input type="time" name="end_time" defaultValue={String(t.end_time).slice(0,5)} required/><input type="number" name="default_count" min="0" defaultValue={t.default_count??''}/><input name="note" defaultValue={t.note??''}/><button className="secondaryButton">儲存</button></form><div className="subActions"><form action={duplicateAttendanceTemplate}><input type="hidden" name="id" value={t.id}/><button className="secondaryButton">複製</button></form><form action={deleteAttendanceTemplate}><input type="hidden" name="id" value={t.id}/><button className="dangerButton">刪除</button></form></div></article>)}</div>
    </section>

    <section className="card"><div className="sectionTitle"><div><span>02</span><h2>整月一鍵帶入</h2></div><strong>{selectedMonth}</strong></div><form action={applyTemplatesToMonth} className="monthApply"><label>月份<input type="month" name="month" defaultValue={selectedMonth} required/></label><button className="primaryButton">⚡ 套用整個月份</button><span className="muted">會重建該月模板來源；手動例外保留。</span></form></section>

    <section className="card"><div className="sectionTitle"><div><span>03</span><h2>某一天實際出勤</h2></div><strong>{selectedDate}</strong></div><form method="get" className="dateBar"><input type="date" name="date" defaultValue={selectedDate}/><input type="hidden" name="month" value={selectedMonth}/><button className="secondaryButton">查看日期</button></form><form action={applyTemplateToDate} className="dateBar"><input type="hidden" name="attendance_date" value={selectedDate}/><button className="primaryButton">⚡ 只重套這一天</button></form>
      <form action={addDailyAttendanceSegment} className="gridForm"><input type="hidden" name="attendance_date" value={selectedDate}/><label>方式<select name="mode"><option value="grade">依年級</option><option value="individual">依個人</option></select></label><label>年級<select name="grade"><option value="">—</option>{[1,2,3,4,5,6].map(g=><option key={g} value={g}>{g}年級</option>)}</select></label><label>學生<select name="student_id"><option value="">—</option>{(students??[]).map(s=><option key={s.id} value={s.id}>{s.display_name}</option>)}</select></label><label>開始<input type="time" name="start_time" required/></label><label>結束<input type="time" name="end_time" required/></label><label>實際人數<input type="number" name="attendee_count" min="0"/></label><label>備註<input name="note"/></label><button className="primaryButton wide">＋ 新增例外</button></form>
      <div className="dailyEditList">{(segments??[]).length===0?<p className="muted">{selectedDate} 尚無出勤時段。</p>:(segments??[]).map(s=><article key={s.id}><form action={updateDailyAttendanceSegment} className="dailyRow"><input type="hidden" name="id" value={s.id}/><input type="hidden" name="attendance_date" value={selectedDate}/><select name="mode" defaultValue={s.mode}><option value="grade">年級</option><option value="individual">個人</option></select><select name="grade" defaultValue={s.grade??''}><option value="">—</option>{[1,2,3,4,5,6].map(g=><option key={g} value={g}>{g}年</option>)}</select><select name="student_id" defaultValue={s.student_id??''}><option value="">—</option>{(students??[]).map(st=><option key={st.id} value={st.id}>{st.display_name}</option>)}</select><input type="time" name="start_time" defaultValue={String(s.start_time).slice(0,5)}/><input type="time" name="end_time" defaultValue={String(s.end_time).slice(0,5)}/><input type="number" name="attendee_count" min="0" defaultValue={s.attendee_count??''}/><input name="note" defaultValue={s.note??''}/><button className="secondaryButton">儲存</button></form><div className="rowMeta"><span>{s.source==='template'?'由模板帶入':'手動調整'}</span><form action={deleteDailyAttendanceSegment}><input type="hidden" name="id" value={s.id}/><input type="hidden" name="attendance_date" value={selectedDate}/><button className="dangerButton">刪除</button></form></div></article>)}</div>
    </section>

    <section className="card"><div className="sectionTitle"><div><span>04</span><h2>建議流程</h2></div></div><div className="notice"><b>學期初：</b>設定週模板。<br/><b>每月初：</b>整月套用一次。<br/><b>每天：</b>只修改請假、臨時加課、提早離開。</div></section>
    <style>{`.gridForm{display:grid;grid-template-columns:repeat(4,1fr);gap:9px;margin-top:12px}.gridForm label,.monthApply label{font-size:12px;font-weight:800;color:#637083}.gridForm input,.gridForm select,.monthApply input{display:block;width:100%;margin-top:6px;padding:10px 11px;border:1px solid #dce2e8;border-radius:11px;background:#fff;font:inherit}.gridForm .wide{grid-column:1/-1}.editableTableWrap,.dailyEditList{display:grid;gap:8px;margin-top:14px}.editRow,.dailyEditList article{padding:8px;border:1px solid #e1e6eb;border-radius:14px;background:#fff}.rowForm{display:grid;grid-template-columns:80px 80px 75px 140px 100px 100px 80px minmax(130px,1fr) 70px;gap:6px}.dailyRow{display:grid;grid-template-columns:80px 75px 150px 100px 100px 80px minmax(130px,1fr) 70px;gap:6px}.rowForm input,.rowForm select,.dailyRow input,.dailyRow select{width:100%;padding:8px;border:1px solid #dce2e8;border-radius:9px;background:#fff}.subActions,.rowMeta{display:flex;gap:6px;align-items:center;margin-top:6px}.rowMeta{justify-content:space-between;color:#748191;font-size:12px}.subActions form,.rowMeta form{margin:0}.dateBar,.monthApply{display:flex;gap:10px;align-items:end;margin:10px 0}.dateBar input{padding:10px;border:1px solid #dce2e8;border-radius:10px}.monthApply label{min-width:180px}@media(max-width:1000px){.rowForm,.dailyRow{grid-template-columns:repeat(4,1fr)}}@media(max-width:850px){.gridForm{grid-template-columns:1fr 1fr}}@media(max-width:560px){.gridForm,.rowForm,.dailyRow{grid-template-columns:1fr}.gridForm .wide{grid-column:auto}.dateBar,.monthApply{align-items:stretch;flex-direction:column}}`}</style>
  </main>;
}
