import Link from 'next/link';
import {notFound} from 'next/navigation';
import {createClient} from '@/lib/supabase/server';
import {publicThemeStyle} from '@/lib/public-theme';

type PublicTeam={name:string;short_name:string|null;school_name:string|null;logo_data_url:string|null;brand_color:string|null;tagline:string|null;public_description:string|null;public_modules:Record<string,unknown>|null};
const MODULES=[['standards','📘','球隊規範','訓練、請假、比賽與家長配合原則'],['rubber_guide','🔴','球皮介紹','球皮類型與選擇方向'],['blade_guide','🏓','球板介紹','純木、纖維與球板結構'],['career_guide','🌱','桌球職涯','競賽、升學與發展方向'],['service_rules','🛠️','代工規則','球皮／球板更換與代工服務']] as const;
function bool(mods:Record<string,unknown>,key:string,def=true){const v=mods[key];return typeof v==='boolean'?v:def}
export default async function PublicMorePage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const supabase=await createClient();const {data:rows}=await supabase.rpc('get_public_team',{target_slug:slug});const team=rows?.[0] as PublicTeam|undefined;if(!team)notFound();const mods=team.public_modules||{};return <main className="publicMore" style={publicThemeStyle(mods,team.brand_color)}><header><div>{team.logo_data_url?<img src={team.logo_data_url} alt="團隊 Logo"/>:<span>🏓</span>}</div><h1>{team.short_name||team.name}</h1><p>{team.tagline||team.public_description||team.school_name||'家長資訊站'}</p></header><section><h2>更多資訊</h2><div className="moreGrid">{MODULES.filter(([k])=>bool(mods,k,true)).map(([k,icon,title,desc])=>{const full=bool(mods,`full_${k}`,false);const href=full?`/p/${slug}/full/${k}`:`/p/${slug}/info/${k}`;return <Link href={href} key={k}><span>{icon}</span><div><b>{title}</b><small>{desc}{full?' · 完整版':''}</small></div><i>›</i></Link>})}</div></section><style>{`.publicMore{min-height:100vh;padding:30px 16px 110px;background:linear-gradient(180deg,var(--public-page),color-mix(in srgb,var(--public-page) 72%,white));color:var(--public-text)}.publicMore>header,.publicMore>section{max-width:850px;margin:auto}.publicMore>header{text-align:center;padding:20px 0 26px}.publicMore>header>div{width:82px;height:82px;margin:auto;border-radius:25px;background:var(--public-card);border:3px solid var(--public-primary);display:grid;place-items:center;overflow:hidden;box-shadow:0 10px 28px #2f36421b}.publicMore>header img{width:100%;height:100%;object-fit:contain}.publicMore>header span{font-size:36px}.publicMore h1{margin:12px 0 4px;font-size:28px}.publicMore p{margin:0;color:#758194}.publicMore section h2{font-size:17px;margin:0 0 10px}.moreGrid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.moreGrid a{text-decoration:none;color:inherit;background:var(--public-card);border:1px solid var(--public-border);border-radius:20px;padding:16px;display:grid;grid-template-columns:42px 1fr auto;gap:10px;align-items:center;box-shadow:0 8px 22px #2f36420d}.moreGrid a:hover{border-color:var(--public-primary);background:linear-gradient(135deg,var(--public-card),var(--public-soft))}.moreGrid a>span{font-size:24px}.moreGrid a div{display:grid;gap:3px}.moreGrid small{color:#7b8798}.moreGrid i{font-style:normal;color:var(--public-primary);font-size:22px}@media(max-width:640px){.moreGrid{grid-template-columns:1fr}}`}</style></main>}
