import {notFound} from 'next/navigation';
import {createClient} from '@/lib/supabase/server';
import PublicCompetitionGallery from '@/components/PublicCompetitionGallery';

type PublicTeam={name:string;short_name:string|null;brand_color:string|null;public_modules:Record<string,unknown>|null};
type Competition={id:string;name:string;start_date:string;end_date:string|null;location:string|null;registration_deadline:string|null;status:string;public_show_roster:boolean;public_meeting_time:string|null;public_meeting_place:string|null;public_clothing:string|null;public_notes:string|null;public_official_url:string|null;public_image_url:string|null;public_image_urls:string[]|null};
type RosterRow={student_name:string;competition_date:string|null;category:string|null};
const STATUS:Record<string,string>={planning:'規劃中',open:'進行中',closed:'已截止',completed:'已完成'};
function dateLabel(v:string|null){if(!v)return '';const [y,m,d]=v.split('-');return `${y}/${m}/${d}`}
function nowDate(){const p=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const m=Object.fromEntries(p.map(x=>[x.type,x.value]));return `${m.year}-${m.month}-${m.day}`}

export default async function PublicCompetitionsPage({params}:{params:Promise<{slug:string}>}){
  const {slug}=await params;const supabase=await createClient();const {data:teamRows}=await supabase.rpc('get_public_team',{target_slug:slug});const team=teamRows?.[0] as PublicTeam|undefined;
  if(!team||team.public_modules?.competitions===false)notFound();
  const {data}=await supabase.rpc('get_public_competitions',{target_slug:slug});const all=((data||[]) as Competition[]).filter(c=>c.status!=='cancelled');const today=nowDate();const upcoming=all.filter(c=>(c.end_date||c.start_date)>=today&&c.status!=='completed');const past=all.filter(c=>(c.end_date||c.start_date)<today||c.status==='completed').reverse();
  const rosterMap=new Map<string,RosterRow[]>();for(const c of all.filter(x=>x.public_show_roster)){const {data:r}=await supabase.rpc('get_public_competition_roster',{target_slug:slug,target_competition:c.id});rosterMap.set(c.id,(r||[]) as RosterRow[])}
  const cards=(rows:Competition[])=>rows.map(c=>{const roster=rosterMap.get(c.id)||[];const hasParentDetails=c.public_meeting_time||c.public_meeting_place||c.public_clothing||c.public_notes;const images=(c.public_image_urls?.length?c.public_image_urls:(c.public_image_url?[c.public_image_url]:[])).filter(Boolean);return <article className="publicCompetitionCard" key={c.id}>{images.length?<PublicCompetitionGallery images={images} name={c.name}/>:null}<div className="compTop"><div><span>{STATUS[c.status]||c.status}</span><h2>{c.name}</h2></div><b>{dateLabel(c.start_date)}</b></div><div className="compMeta"><span>📅 {dateLabel(c.start_date)}{c.end_date&&c.end_date!==c.start_date?` ～ ${dateLabel(c.end_date)}`:''}</span>{c.location?<span>📍 {c.location}</span>:null}{c.registration_deadline?<span>⏰ 報名截止 {dateLabel(c.registration_deadline)}</span>:null}</div>{c.public_official_url?<a className="officialLink" href={c.public_official_url} target="_blank" rel="noreferrer">🌐 大會／官方資訊 ›</a>:null}{hasParentDetails?<div className="parentDetails">{c.public_meeting_time?<div><small>集合時間</small><b>🕐 {c.public_meeting_time}</b></div>:null}{c.public_meeting_place?<div><small>集合地點</small><b>📍 {c.public_meeting_place}</b></div>:null}{c.public_clothing?<div><small>穿著</small><b>👕 {c.public_clothing}</b></div>:null}{c.public_notes?<div className="wide"><small>注意事項</small><p>{c.public_notes}</p></div>:null}</div>:null}{c.public_show_roster?<div className="rosterBox"><strong>公開參賽名單</strong>{roster.length?<div className="rosterChips">{Array.from(new Set(roster.map(r=>r.student_name))).map(name=><span key={name}>{name}</span>)}</div>:<small>目前尚未登記參賽名單。</small>}</div>:null}</article>});
  return <main className="publicSubPage" style={{'--brand':team.brand_color||'#7c3aed'} as React.CSSProperties}><header><span>家長資訊站</span><h1>比賽資訊</h1><p>{team.short_name||team.name}近期賽事與集合資訊。</p></header><section className="publicListShell"><div className="sectionHead"><h2>即將到來</h2><span>{upcoming.length} 場</span></div>{upcoming.length?cards(upcoming):<div className="emptyState">目前沒有即將到來的公開比賽。</div>}{past.length?<><div className="sectionHead pastHead"><h2>過往比賽</h2><span>{past.length} 場</span></div>{cards(past.slice(0,8))}</>:null}</section>
    <style>{`.publicSubPage{min-height:100vh;padding-bottom:100px;background:linear-gradient(180deg,#f7f4ff,#f8fcfc);color:#182234}.publicSubPage>header{padding:34px 20px 44px;background:linear-gradient(135deg,var(--brand),#ec4899 55%,#16b8aa);color:#fff}.publicSubPage>header>*{display:block;max-width:850px;margin-left:auto;margin-right:auto}.publicSubPage>header span{font-size:12px;font-weight:900;opacity:.9}.publicSubPage>header h1{font-size:32px;margin-top:5px;margin-bottom:4px}.publicSubPage>header p{margin-top:0;opacity:.9}.publicListShell{max-width:850px;margin:-18px auto 0;padding:0 16px;display:grid;gap:12px}.sectionHead{display:flex;align-items:center;justify-content:space-between;padding:16px 3px 2px}.sectionHead h2{font-size:18px;margin:0}.sectionHead span{font-size:11px;color:#7c8797}.pastHead{margin-top:4px}.publicCompetitionCard,.emptyState{background:#fff;border:1px solid #e4e1ec;border-radius:22px;padding:18px;box-shadow:0 10px 28px #6b5d8b12}.compTop{display:flex;justify-content:space-between;align-items:flex-start;gap:15px}.compTop span{display:inline-block;background:#f0e9ff;color:var(--brand);border-radius:999px;padding:5px 8px;font-size:10px;font-weight:900}.compTop h2{margin:7px 0 0;font-size:19px}.compTop>b{font-size:13px;color:#69768a;white-space:nowrap}.compMeta{display:flex;gap:8px 14px;flex-wrap:wrap;margin-top:13px;color:#6c788a;font-size:12px}.officialLink{display:inline-block;margin-top:12px;color:var(--brand);font-size:12px;font-weight:900;text-decoration:none}.parentDetails{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:14px}.parentDetails>div{padding:11px;border-radius:14px;background:#f7f4ff}.parentDetails small{display:block;color:#8993a2;font-size:10px;margin-bottom:4px}.parentDetails b{font-size:12px}.parentDetails .wide{grid-column:1/-1}.parentDetails p{margin:0;white-space:pre-wrap;color:#5e6a7a;line-height:1.6;font-size:12px}.rosterBox{margin-top:14px;padding-top:13px;border-top:1px solid #eef0f3}.rosterBox strong{display:block;font-size:12px;margin-bottom:8px}.rosterBox small{color:#8290a1}.rosterChips{display:flex;flex-wrap:wrap;gap:6px}.rosterChips span{background:#f6f3fb;border-radius:999px;padding:6px 9px;font-size:11px;color:#586477}.emptyState{color:#7b8595}@media(max-width:640px){.publicSubPage>header h1{font-size:27px}.compTop{align-items:center}.parentDetails{grid-template-columns:1fr}.parentDetails .wide{grid-column:auto}}`}</style>
  </main>;
}
