import Link from 'next/link';
import { redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';
import { addAirconRun,deleteAirconRun,deleteMeterRecord,importAirconRunsFromAttendance,saveMeterRecord } from './actions';
import { updateAirconRun } from './edit-actions';

type Meter={id:string;record_month:string;opening_reading:number;closing_reading:number;rate_per_unit:number;fixed_fee:number;note:string|null};
type Run={id:string;meter_record_id:string|null;usage_date:string;start_time:string;end_time:string;note:string|null;source?:string};
const pad=(n:number)=>String(n).padStart(2,'0');
const currentMonth=()=>{const d=new Date();return `${d.getFullYear()}-${pad(d.getMonth()+1)}`};

export default async function AirconPage({searchParams}:{searchParams:Promise<{month?:string;message?:string;error?:string}>}){
  const q=await searchParams;const month=q.month||currentMonth();const monthStart=`${month}-01`;const endDate=new Date(Number(month.slice(0,4)),Number(month.slice(5,7)),1);const nextMonth=`${endDate.getFullYear()}-${pad(endDate.getMonth()+1)}-01`;
  const supabase=await createClient();const {data:claims}=await supabase.auth.getClaims();if(!claims?.claims?.sub)redirect('/login');const {data:teamId}=await supabase.rpc('current_team_id');if(!teamId)redirect('/more');
  const [{data:meterHistory},{data:runs}]=await Promise.all([
    supabase.from('aircon_meter_records').select('id,record_month,opening_reading,closing_reading,rate_per_unit,fixed_fee,note').eq('team_id',teamId).order('record_month',{ascending:false}).limit(18),
    supabase.from('aircon_runs').select('id,meter_record_id,usage_date,start_time,end_time,note,source').eq('team_id',teamId).gte('usage_date',monthStart).lt('usage_date',nextMonth).order('usage_date').order('start_time'),
  ]);
  const meters=(meterHistory??[]) as Meter[],meter=meters.find(m=>String(m.record_month).slice(0,7)===month),runList=(runs??[]) as Run[];const units=meter?Number(meter.closing_reading)-Number(meter.opening_reading):0,totalCost=meter?units*Number(meter.rate_per_unit)+Number(meter.fixed_fee):0;

  return <main className="shell">
    <section className="hero compactHero"><div className="eyebrow">AIRCON V4</div><h1>冷氣登記與費用</h1><p>冷氣時段直接從整月學生出勤帶入，不再分年級；月底分攤先暫停，等實際帶入資料確認後再測算。</p><div className="topNav"><Link href="/attendance-settings">學生出勤</Link><Link href="/payroll">教練薪酬</Link><Link href="/more">更多</Link></div></section>
    {q.message?<div className="notice successNotice">{q.message}</div>:null}{q.error?<div className="notice errorNotice">{q.error}</div>:null}

    <section className="card"><div className="sectionTitle"><div><span>01</span><h2>月份</h2></div><strong>{month}</strong></div><form method="get" className="inline"><input type="month" name="month" defaultValue={month}/><button className="secondaryButton">切換月份</button></form></section>

    <section className="card"><div className="sectionTitle"><div><span>02</span><h2>本月電表結算</h2></div><strong>{meter?`${units.toFixed(2)} 度`:'尚未登記'}</strong></div><form action={saveMeterRecord} className="grid"><label>月份<input type="month" name="record_month" defaultValue={month} required/></label><label>月初電表<input type="number" step="0.01" name="opening_reading" defaultValue={meter?.opening_reading??''} required/></label><label>月底電表<input type="number" step="0.01" name="closing_reading" defaultValue={meter?.closing_reading??''} required/></label><label>每度單價<input type="number" step="0.0001" name="rate_per_unit" defaultValue={meter?.rate_per_unit??''} required/></label><label>固定費<input type="number" name="fixed_fee" defaultValue={meter?.fixed_fee??0}/></label><label className="wide">備註<input name="note" defaultValue={meter?.note??''}/></label><button className="primaryButton wide">儲存／更新這個月份</button></form>{meter?<div className="summary"><span>本月用電 <b>{units.toFixed(2)} 度</b></span><span>應繳學校 <b>${Math.round(totalCost).toLocaleString()}</b></span></div>:null}</section>

    <section className="card"><div className="sectionTitle"><div><span>03</span><h2>月份電表歷史</h2></div><strong>{meters.length} 個月</strong></div><div className="historyGrid">{meters.map(m=>{const u=Number(m.closing_reading)-Number(m.opening_reading);const c=u*Number(m.rate_per_unit)+Number(m.fixed_fee);const mth=String(m.record_month).slice(0,7);return <article key={m.id}><Link href={`/aircon?month=${mth}`}><b>{mth}</b><span>{u.toFixed(2)} 度</span><strong>${Math.round(c).toLocaleString()}</strong></Link><form action={deleteMeterRecord}><input type="hidden" name="id" value={m.id}/><input type="hidden" name="month" value={month}/><button className="dangerButton">刪除</button></form></article>})}</div></section>

    <section className="card"><div className="sectionTitle"><div><span>04</span><h2>由學生出勤帶入冷氣時間</h2></div><strong>{month}</strong></div><div className="notice">會讀取這個月份「學生出勤」裡已產生的每日時段，整月一次帶入；同一天相連或重疊的時段會自動合併，之後仍可逐筆修改。</div><form action={importAirconRunsFromAttendance} className="inline"><input type="hidden" name="month" value={month}/><button className="primaryButton">⚡ 從整月學生出勤帶入</button></form></section>

    <section className="card"><div className="sectionTitle"><div><span>05</span><h2>每天實際吹冷氣時間</h2></div><strong>{runList.length} 段</strong></div><form action={addAirconRun} className="grid"><input type="hidden" name="meter_record_id" value={meter?.id??''}/><label>日期<input type="date" name="usage_date" required/></label><label>開啟<input type="time" name="start_time" required/></label><label>關閉<input type="time" name="end_time" required/></label><label>備註<input name="note"/></label><button className="primaryButton wide">＋ 新增冷氣時段</button></form><div className="runList">{runList.length===0?<p className="muted">本月還沒有冷氣時段。</p>:runList.map(r=><article key={r.id}><form action={updateAirconRun} className="runEdit"><input type="hidden" name="id" value={r.id}/><input type="date" name="usage_date" defaultValue={r.usage_date}/><input type="time" name="start_time" defaultValue={String(r.start_time).slice(0,5)}/><input type="time" name="end_time" defaultValue={String(r.end_time).slice(0,5)}/><input name="note" defaultValue={r.note??''}/><button className="secondaryButton">儲存</button></form><div className="runMeta"><span>{r.source==='attendance_count'?'由學生出勤帶入':'手動登記'}</span><form action={deleteAirconRun}><input type="hidden" name="id" value={r.id}/><input type="hidden" name="month" value={month}/><button className="dangerButton">刪除</button></form></div></article>)}</div></section>

    <section className="card"><div className="sectionTitle"><div><span>06</span><h2>本月自動分攤</h2></div><strong>暫緩測試</strong></div><div className="notice">先把「學生出勤 → 整月冷氣時段」實際帶入確認正確。等資料流穩定後，再回來測試分攤金額公式，避免現在同時增加 Worker 負擔。</div></section>
    <style>{`.inline{display:flex;gap:9px;align-items:center;margin:10px 0;flex-wrap:wrap}.inline input,.grid input{padding:10px;border:1px solid #dce2e8;border-radius:11px;background:#fff}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:9px}.grid label{font-size:12px;font-weight:800;color:#637083}.grid input{display:block;width:100%;margin-top:6px}.wide{grid-column:1/-1}.summary{display:flex;gap:12px;margin-top:12px}.summary span{flex:1;padding:14px;border-radius:14px;background:var(--theme-soft,#f4f7fa)}.historyGrid{display:grid;grid-template-columns:repeat(4,1fr);gap:9px}.historyGrid article{border:1px solid #e1e6eb;border-radius:14px;padding:10px;background:#fff}.historyGrid a{display:flex;flex-direction:column;gap:4px;text-decoration:none;color:inherit}.historyGrid form{margin-top:8px}.runList{display:grid;gap:8px;margin-top:12px}.runList article{border:1px solid #e1e6eb;border-radius:14px;padding:10px;background:#fff}.runEdit{display:grid;grid-template-columns:160px 110px 110px 1fr 70px;gap:7px}.runEdit input{padding:9px;border:1px solid #dce2e8;border-radius:9px}.runMeta{display:flex;align-items:center;justify-content:space-between;color:#748191;font-size:12px;margin-top:6px}@media(max-width:850px){.grid,.historyGrid{grid-template-columns:1fr 1fr}.runEdit{grid-template-columns:1fr 1fr}}@media(max-width:560px){.inline{align-items:stretch;flex-direction:column}.grid,.historyGrid,.runEdit{grid-template-columns:1fr}.wide{grid-column:auto}}`}</style>
  </main>;
}
