import Link from 'next/link';
import { redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';
import { addAirconRun,deleteAirconRun,importAirconRunsFromGrade,saveMeterRecord,saveMonthAllocation } from './actions';
import { updateAirconRun } from './edit-actions';

type Meter={id:string;record_month:string;opening_reading:number;closing_reading:number;rate_per_unit:number;fixed_fee:number;note:string|null};
type Run={id:string;meter_record_id:string|null;usage_date:string;start_time:string;end_time:string;note:string|null;source?:string;source_grade?:number|null};
type Attendance={attendance_date:string;mode:'grade'|'individual';grade:number|null;student_id:string|null;start_time:string;end_time:string;attendee_count:number|null};
type Student={id:string;display_name:string;grade:number|null};
const pad=(n:number)=>String(n).padStart(2,'0');
const currentMonth=()=>{const d=new Date();return `${d.getFullYear()}-${pad(d.getMonth()+1)}`};
const mins=(t:string)=>{const [h,m]=String(t).slice(0,5).split(':').map(Number);return h*60+m};
const overlap=(a1:string,a2:string,b1:string,b2:string)=>Math.max(0,Math.min(mins(a2),mins(b2))-Math.max(mins(a1),mins(b1)));

export default async function AirconPage({searchParams}:{searchParams:Promise<{month?:string;message?:string;error?:string;calculate?:string}>}){
  const q=await searchParams; const month=q.month||currentMonth(); const calculate=q.calculate==='1'; const monthStart=`${month}-01`;
  const endDate=new Date(Number(month.slice(0,4)),Number(month.slice(5,7)),1); const nextMonth=`${endDate.getFullYear()}-${pad(endDate.getMonth()+1)}-01`;
  const supabase=await createClient(); const {data:claims}=await supabase.auth.getClaims(); if(!claims?.claims?.sub)redirect('/login'); const {data:teamId}=await supabase.rpc('current_team_id'); if(!teamId)redirect('/more');
  const [{data:meterHistory},{data:runs},{data:setting},{data:students},attendanceResult]=await Promise.all([
    supabase.from('aircon_meter_records').select('id,record_month,opening_reading,closing_reading,rate_per_unit,fixed_fee,note').eq('team_id',teamId).order('record_month',{ascending:false}).limit(18),
    supabase.from('aircon_runs').select('id,meter_record_id,usage_date,start_time,end_time,note,source,source_grade').eq('team_id',teamId).gte('usage_date',monthStart).lt('usage_date',nextMonth).order('usage_date').order('start_time'),
    supabase.from('aircon_month_settings').select('allocation_mode').eq('team_id',teamId).eq('record_month',monthStart).maybeSingle(),
    supabase.from('students').select('id,display_name,grade').eq('team_id',teamId).eq('active',true),
    calculate?supabase.from('daily_attendance_segments').select('attendance_date,mode,grade,student_id,start_time,end_time,attendee_count').eq('team_id',teamId).gte('attendance_date',monthStart).lt('attendance_date',nextMonth):Promise.resolve({data:[]} as any),
  ]);
  const meters=(meterHistory??[]) as Meter[]; const meter=meters.find(m=>String(m.record_month).slice(0,7)===month); const runList=(runs??[]) as Run[]; const att=(attendanceResult.data??[]) as Attendance[]; const allocationMode=(setting?.allocation_mode??'grade') as 'grade'|'individual'; const studentMap=new Map<string,Student>(((students??[]) as Student[]).map(s=>[s.id,s]));
  const units=meter?Number(meter.closing_reading)-Number(meter.opening_reading):0; const totalCost=meter?units*Number(meter.rate_per_unit)+Number(meter.fixed_fee):0;
  const weights=new Map<string,number>();
  if(calculate){const attByDate=new Map<string,Attendance[]>();for(const a of att){const list=attByDate.get(a.attendance_date)??[];list.push(a);attByDate.set(a.attendance_date,list);}for(const r of runList){for(const a of attByDate.get(r.usage_date)??[]){const ov=overlap(r.start_time,r.end_time,a.start_time,a.end_time);if(ov<=0)continue;if(allocationMode==='grade'){if(a.mode==='grade'&&a.grade){const k=`${a.grade}年級`;weights.set(k,(weights.get(k)??0)+ov*Number(a.attendee_count??0));}else if(a.mode==='individual'&&a.student_id){const g=studentMap.get(a.student_id)?.grade;if(g){const k=`${g}年級`;weights.set(k,(weights.get(k)??0)+ov);}}}else if(a.mode==='individual'&&a.student_id){weights.set(a.student_id,(weights.get(a.student_id)??0)+ov);}}}}
  const totalWeight=[...weights.values()].reduce((a,b)=>a+b,0); const allocations=[...weights.entries()].map(([key,weight])=>({key,label:allocationMode==='individual'?(studentMap.get(key)?.display_name??'未知學生'):key,weight,amount:totalWeight?totalCost*weight/totalWeight:0})).sort((a,b)=>b.amount-a.amount);

  return <main className="shell">
    <section className="hero compactHero"><div className="eyebrow">AIRCON V3 · LITE</div><h1>冷氣登記與費用分攤</h1><p>日常登記與月底運算分開：平常開頁不掃整月出勤，只有按「計算本月分攤」時才進行加權計算。</p><div className="topNav"><Link href="/attendance-settings">出勤／時段設定</Link><Link href="/payroll">教練薪酬</Link><Link href="/more">更多</Link></div></section>
    {q.message?<div className="notice successNotice">{q.message}</div>:null}{q.error?<div className="notice errorNotice">{q.error}</div>:null}

    <section className="card"><div className="sectionTitle"><div><span>01</span><h2>月份與分攤方式</h2></div></div><form method="get" className="inline"><input type="month" name="month" defaultValue={month}/><button className="secondaryButton">切換月份</button></form><form action={saveMonthAllocation} className="inline"><input type="hidden" name="record_month" value={month}/><select name="allocation_mode" defaultValue={allocationMode}><option value="grade">依年級分攤</option><option value="individual">依個人分攤</option></select><button className="primaryButton">儲存分攤方式</button></form></section>

    <section className="card"><div className="sectionTitle"><div><span>02</span><h2>本月電表結算</h2></div><strong>{meter?`${units.toFixed(2)} 度`:'尚未登記'}</strong></div><form action={saveMeterRecord} className="grid"><label>月份<input type="month" name="record_month" defaultValue={month} required/></label><label>月初電表<input type="number" step="0.01" name="opening_reading" defaultValue={meter?.opening_reading??''} required/></label><label>月底電表<input type="number" step="0.01" name="closing_reading" defaultValue={meter?.closing_reading??''} required/></label><label>每度單價<input type="number" step="0.0001" name="rate_per_unit" defaultValue={meter?.rate_per_unit??''} required/></label><label>固定費<input type="number" name="fixed_fee" defaultValue={meter?.fixed_fee??0}/></label><label className="wide">備註<input name="note" defaultValue={meter?.note??''}/></label><button className="primaryButton wide">儲存／更新這個月份</button></form>{meter?<div className="summary"><span>本月用電 <b>{units.toFixed(2)} 度</b></span><span>應繳學校 <b>${Math.round(totalCost).toLocaleString()}</b></span></div>:null}</section>

    <section className="card"><div className="sectionTitle"><div><span>03</span><h2>月份電表歷史</h2></div><strong>{meters.length} 個月</strong></div><div className="historyGrid">{meters.map(m=>{const u=Number(m.closing_reading)-Number(m.opening_reading);const c=u*Number(m.rate_per_unit)+Number(m.fixed_fee);return <Link key={m.id} href={`/aircon?month=${String(m.record_month).slice(0,7)}`}><b>{String(m.record_month).slice(0,7)}</b><span>{u.toFixed(2)} 度</span><strong>${Math.round(c).toLocaleString()}</strong></Link>})}</div></section>

    <section className="card"><div className="sectionTitle"><div><span>04</span><h2>由年級出勤帶入冷氣時間</h2></div><strong>{month}</strong></div><form action={importAirconRunsFromGrade} className="inline"><input type="hidden" name="month" value={month}/><select name="grade">{[1,2,3,4,5,6].map(g=><option value={g} key={g}>{g} 年級</option>)}</select><button className="primaryButton">⚡ 整月帶入</button></form></section>

    <section className="card"><div className="sectionTitle"><div><span>05</span><h2>每天實際吹冷氣時間</h2></div><strong>{runList.length} 段</strong></div><form action={addAirconRun} className="grid"><input type="hidden" name="meter_record_id" value={meter?.id??''}/><label>日期<input type="date" name="usage_date" required/></label><label>開啟<input type="time" name="start_time" required/></label><label>關閉<input type="time" name="end_time" required/></label><label>備註<input name="note"/></label><button className="primaryButton wide">＋ 新增冷氣時段</button></form><div className="runList">{runList.length===0?<p className="muted">本月還沒有冷氣時段。</p>:runList.map(r=><article key={r.id}><form action={updateAirconRun} className="runEdit"><input type="hidden" name="id" value={r.id}/><input type="date" name="usage_date" defaultValue={r.usage_date}/><input type="time" name="start_time" defaultValue={String(r.start_time).slice(0,5)}/><input type="time" name="end_time" defaultValue={String(r.end_time).slice(0,5)}/><input name="note" defaultValue={r.note??''}/><button className="secondaryButton">儲存</button></form><div className="runMeta"><span>{r.source==='attendance_grade'?`由 ${r.source_grade} 年級帶入`:'手動登記'}</span><form action={deleteAirconRun}><input type="hidden" name="id" value={r.id}/><input type="hidden" name="month" value={month}/><button className="dangerButton">刪除</button></form></div></article>)}</div></section>

    <section className="card"><div className="sectionTitle"><div><span>06</span><h2>本月自動分攤</h2></div><strong>{allocationMode==='grade'?'依年級':'依個人'}</strong></div>{!calculate?<><div className="notice">為降低 Worker 負擔，整月出勤加權改成需要時才計算。</div><Link className="primaryButton calcButton" href={`/aircon?month=${month}&calculate=1`}>計算本月分攤</Link></>:!meter?<div className="notice">先登記本月電表與費率。</div>:runList.length===0?<div className="notice">先登記或帶入冷氣時段。</div>:totalWeight===0?<div className="notice errorNotice">找不到符合分攤方式的出勤資料。</div>:<><div className="allocationGrid">{allocations.map(x=><article key={x.key}><b>{x.label}</b><strong>${Math.round(x.amount).toLocaleString()}</strong><span>{allocationMode==='grade'?`${Math.round(x.weight)} 人分鐘`:`${Math.round(x.weight)} 分鐘`}</span><small>{(x.weight/totalWeight*100).toFixed(1)}%</small></article>)}</div><div className="notice" style={{marginTop:12}}>分攤總額 ${Math.round(totalCost).toLocaleString()}。</div></>}</section>
    <style>{`.inline{display:flex;gap:9px;align-items:center;margin:10px 0;flex-wrap:wrap}.inline input,.inline select,.grid input,.grid select{padding:10px;border:1px solid #dce2e8;border-radius:11px;background:#fff}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:9px}.grid label{font-size:12px;font-weight:800;color:#637083}.grid input{display:block;width:100%;margin-top:6px}.wide{grid-column:1/-1}.summary{display:flex;gap:12px;margin-top:12px}.summary span{flex:1;padding:14px;border-radius:14px;background:var(--theme-soft,#f4f7fa)}.historyGrid,.allocationGrid{display:grid;grid-template-columns:repeat(4,1fr);gap:9px}.historyGrid a,.allocationGrid article{display:flex;flex-direction:column;gap:4px;text-decoration:none;color:inherit;border:1px solid #e1e6eb;border-radius:14px;padding:12px;background:#fff}.runList{display:grid;gap:8px;margin-top:12px}.runList article{border:1px solid #e1e6eb;border-radius:14px;padding:10px;background:#fff}.runEdit{display:grid;grid-template-columns:160px 110px 110px 1fr 70px;gap:7px}.runEdit input{padding:9px;border:1px solid #dce2e8;border-radius:9px}.runMeta{display:flex;align-items:center;justify-content:space-between;color:#748191;font-size:12px;margin-top:6px}.calcButton{display:inline-block;text-decoration:none;margin-top:10px}@media(max-width:850px){.grid,.historyGrid,.allocationGrid{grid-template-columns:1fr 1fr}.runEdit{grid-template-columns:1fr 1fr}}@media(max-width:560px){.inline{align-items:stretch;flex-direction:column}.grid,.historyGrid,.allocationGrid,.runEdit{grid-template-columns:1fr}.wide{grid-column:auto}}`}</style>
  </main>;
}
