import Link from 'next/link';
import { redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';
import { addCoachAttendance,addCoachScheduleTemplate,addFinanceItem,applyCoachTemplatesToDate,deleteCoachAttendance,deleteCoachScheduleTemplate,deleteFinanceItem,saveCoachPayRule } from './actions';

const WEEK=['一','二','三','四','五','六','日'];
const pad=(n:number)=>String(n).padStart(2,'0');
const nowParts=()=>{const d=new Date();return {date:`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`,month:`${d.getFullYear()}-${pad(d.getMonth()+1)}`}};
const tm=(t:string)=>{const [h,m]=String(t).slice(0,5).split(':').map(Number);return h*60+m};
const ov=(a1:string,a2:string,b1:string,b2:string)=>Math.max(0,Math.min(tm(a2),tm(b2))-Math.max(tm(a1),tm(b1)));

type Rule={coach_user_id:string;method:string;hourly_rate:number;base_hourly_rate:number;per_student_hour:number;tier_rules:any[];note:string|null};
type Work={id:string;coach_user_id:string;work_date:string;start_time:string;end_time:string;student_count:number|null;scope_type:string;grade:number|null;training_group_id:string|null;source:string;note:string|null};
type Att={attendance_date:string;mode:string;grade:number|null;student_id:string|null;start_time:string;end_time:string;attendee_count:number|null};

export default async function PayrollPage({searchParams}:{searchParams:Promise<{month?:string;date?:string;message?:string;error?:string}>}){
  const q=await searchParams;const n=nowParts();const month=q.month||n.month;const date=q.date||n.date;const monthStart=`${month}-01`;const nx=new Date(Number(month.slice(0,4)),Number(month.slice(5,7)),1);const nextMonth=`${nx.getFullYear()}-${pad(nx.getMonth()+1)}-01`;
  const supabase=await createClient();const {data:claims}=await supabase.auth.getClaims();if(!claims?.claims?.sub)redirect('/login');const {data:teamId}=await supabase.rpc('current_team_id');if(!teamId)redirect('/more');
  const [{data:members},{data:profiles},{data:groups},{data:rules},{data:templates},{data:works},{data:attendance},{data:students},{data:finance},{data:meter}]=await Promise.all([
    supabase.from('team_members').select('user_id,member_role').eq('team_id',teamId),
    supabase.from('profiles').select('id,display_name,email'),
    supabase.from('training_groups').select('id,name').eq('team_id',teamId).eq('active',true).order('sort_order'),
    supabase.from('coach_pay_rules').select('coach_user_id,method,hourly_rate,base_hourly_rate,per_student_hour,tier_rules,note').eq('team_id',teamId),
    supabase.from('coach_schedule_templates').select('id,coach_user_id,weekday,start_time,end_time,scope_type,grade,training_group_id,note').eq('team_id',teamId).eq('active',true).order('weekday').order('start_time'),
    supabase.from('coach_attendance_segments').select('id,coach_user_id,work_date,start_time,end_time,student_count,scope_type,grade,training_group_id,source,note').eq('team_id',teamId).gte('work_date',monthStart).lt('work_date',nextMonth).order('work_date').order('start_time'),
    supabase.from('daily_attendance_segments').select('attendance_date,mode,grade,student_id,start_time,end_time,attendee_count').eq('team_id',teamId).gte('attendance_date',monthStart).lt('attendance_date',nextMonth),
    supabase.from('students').select('id,display_name,grade,training_group_id').eq('team_id',teamId).eq('active',true),
    supabase.from('finance_items').select('id,record_month,item_type,category,description,amount').eq('team_id',teamId).eq('record_month',monthStart).order('created_at'),
    supabase.from('aircon_meter_records').select('opening_reading,closing_reading,rate_per_unit,fixed_fee').eq('team_id',teamId).eq('record_month',monthStart).maybeSingle(),
  ]);
  const profileMap=new Map((profiles??[]).map(p=>[p.id,p]));const coachIds=new Set((members??[]).map(m=>m.user_id));const coaches=(profiles??[]).filter(p=>coachIds.has(p.id));const groupMap=new Map((groups??[]).map(g=>[g.id,g.name]));const studentMap=new Map((students??[]).map(s=>[s.id,s]));const ruleMap=new Map((rules??[]).map(r=>[r.coach_user_id,r as Rule]));const att=(attendance??[]) as Att[];const workList=(works??[]) as Work[];
  const estimateCount=(w:Work)=>{if(w.student_count!=null)return Number(w.student_count);const same=att.filter(a=>a.attendance_date===w.work_date&&ov(w.start_time,w.end_time,a.start_time,a.end_time)>0);const indiv=same.filter(a=>a.mode==='individual'&&a.student_id);if(indiv.length){const ids=new Set(indiv.filter(a=>{const s=a.student_id?studentMap.get(a.student_id):null;if(!s)return false;if(w.scope_type==='grade')return Number(s.grade)===Number(w.grade);if(w.scope_type==='group')return s.training_group_id===w.training_group_id;return true}).map(a=>a.student_id));return ids.size;}const grades=same.filter(a=>a.mode==='grade');if(w.scope_type==='group')return 0;return grades.filter(a=>w.scope_type!=='grade'||Number(a.grade)===Number(w.grade)).reduce((sum,a)=>sum+Number(a.attendee_count??0),0)};
  const calcPay=(w:Work)=>{const r=ruleMap.get(w.coach_user_id);if(!r)return 0;const hours=(tm(w.end_time)-tm(w.start_time))/60;const count=estimateCount(w);if(r.method==='base_plus_student')return hours*(Number(r.base_hourly_rate)+Number(r.per_student_hour)*count);if(r.method==='tiered'){const tier=(r.tier_rules??[]).find((x:any)=>count>=Number(x.min??0)&&(x.max==null||count<=Number(x.max)));return hours*Number(tier?.rate??0)}return hours*Number(r.hourly_rate)};
  const coachTotals=new Map<string,number>();for(const w of workList)coachTotals.set(w.coach_user_id,(coachTotals.get(w.coach_user_id)??0)+calcPay(w));const salaryTotal=[...coachTotals.values()].reduce((a,b)=>a+b,0);const income=(finance??[]).filter(x=>x.item_type==='income').reduce((a,x)=>a+Number(x.amount),0);const manualExpense=(finance??[]).filter(x=>x.item_type==='expense').reduce((a,x)=>a+Number(x.amount),0);const airconCost=meter?(Number(meter.closing_reading)-Number(meter.opening_reading))*Number(meter.rate_per_unit)+Number(meter.fixed_fee):0;const net=income-manualExpense-salaryTotal-airconCost;
  const dayWorks=workList.filter(w=>w.work_date===date);
  return <main className="shell">
    <section className="hero compactHero"><div className="eyebrow">COACH PAYROLL & FINANCE</div><h1>教練薪酬與月結</h1><p>固定班表平常直接套用；實際薪酬依工作時間與時段學生數計算，再和營收、其他支出、冷氣費一起做月結。</p><div className="topNav"><Link href="/attendance-settings">學生出勤時段</Link><Link href="/aircon">冷氣費</Link><Link href="/more">更多</Link></div></section>
    {q.message?<div className="notice successNotice">{q.message}</div>:null}{q.error?<div className="notice errorNotice">{q.error}</div>:null}

    <section className="card"><div className="sectionTitle"><div><span>01</span><h2>每位教練計薪規則</h2></div></div><div className="coachRuleGrid">{coaches.map(c=>{const r=ruleMap.get(c.id);return <form action={saveCoachPayRule} key={c.id} className="ruleCard"><input type="hidden" name="coach_user_id" value={c.id}/><h3>{c.display_name||c.email||'教練'}</h3><label>計薪方式<select name="method" defaultValue={r?.method??'hourly'}><option value="hourly">固定時薪</option><option value="tiered">依學生人數級距時薪</option><option value="base_plus_student">基本時薪＋每位學生加成</option></select></label><div className="miniGrid"><label>固定時薪<input type="number" name="hourly_rate" defaultValue={r?.hourly_rate??0}/></label><label>基本時薪<input type="number" name="base_hourly_rate" defaultValue={r?.base_hourly_rate??0}/></label><label>每生／小時加成<input type="number" name="per_student_hour" defaultValue={r?.per_student_hour??0}/></label></div><div className="miniGrid"><label>第一級最多<input type="number" name="tier1_max" defaultValue={5}/></label><label>第一級時薪<input type="number" name="tier1_rate" defaultValue={r?.tier_rules?.[0]?.rate??0}/></label><label>第二級最多<input type="number" name="tier2_max" defaultValue={10}/></label><label>第二級時薪<input type="number" name="tier2_rate" defaultValue={r?.tier_rules?.[1]?.rate??0}/></label><label>第三級以上時薪<input type="number" name="tier3_rate" defaultValue={r?.tier_rules?.[2]?.rate??0}/></label></div><label>備註<input name="note" defaultValue={r?.note??''}/></label><button className="secondaryButton">儲存規則</button></form>})}</div></section>

    <section className="card"><div className="sectionTitle"><div><span>02</span><h2>教練固定每週班表</h2></div><strong>一次設定</strong></div><form action={addCoachScheduleTemplate} className="grid"><label>教練<select name="coach_user_id">{coaches.map(c=><option key={c.id} value={c.id}>{c.display_name||c.email}</option>)}</select></label><label>星期<select name="weekday">{WEEK.map((w,i)=><option key={w} value={i+1}>星期{w}</option>)}</select></label><label>開始<input type="time" name="start_time" required/></label><label>結束<input type="time" name="end_time" required/></label><label>負責範圍<select name="scope_type"><option value="team">全隊</option><option value="grade">年級</option><option value="group">訓練組別</option></select></label><label>年級<select name="grade"><option value="">—</option>{[1,2,3,4,5,6].map(g=><option key={g} value={g}>{g}年級</option>)}</select></label><label>組別<select name="training_group_id"><option value="">—</option>{(groups??[]).map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label><label>備註<input name="note"/></label><button className="primaryButton wide">＋ 新增固定班表</button></form><div className="list">{(templates??[]).map(t=><article key={t.id}><div><b>{profileMap.get(t.coach_user_id)?.display_name||'教練'}｜星期{WEEK[Number(t.weekday)-1]} {String(t.start_time).slice(0,5)}–{String(t.end_time).slice(0,5)}</b><small>{t.scope_type==='team'?'全隊':t.scope_type==='grade'?`${t.grade}年級`:groupMap.get(t.training_group_id)||'組別'}{t.note?`｜${t.note}`:''}</small></div><form action={deleteCoachScheduleTemplate}><input type="hidden" name="id" value={t.id}/><button className="dangerButton">刪除</button></form></article>)}</div></section>

    <section className="card"><div className="sectionTitle"><div><span>03</span><h2>每日實際出勤</h2></div><strong>{date}</strong></div><div className="inline"><form method="get"><input type="date" name="date" defaultValue={date}/><input type="hidden" name="month" value={month}/><button className="secondaryButton">查看日期</button></form><form action={applyCoachTemplatesToDate}><input type="hidden" name="work_date" value={date}/><button className="primaryButton">⚡ 套用這天固定班表</button></form></div><form action={addCoachAttendance} className="grid"><input type="hidden" name="work_date" value={date}/><label>教練<select name="coach_user_id">{coaches.map(c=><option key={c.id} value={c.id}>{c.display_name||c.email}</option>)}</select></label><label>開始<input type="time" name="start_time" required/></label><label>結束<input type="time" name="end_time" required/></label><label>學生數<input type="number" min="0" name="student_count" placeholder="空白＝系統估算"/></label><label>範圍<select name="scope_type"><option value="team">全隊</option><option value="grade">年級</option><option value="group">組別</option></select></label><label>年級<select name="grade"><option value="">—</option>{[1,2,3,4,5,6].map(g=><option key={g} value={g}>{g}年級</option>)}</select></label><label>組別<select name="training_group_id"><option value="">—</option>{(groups??[]).map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label><label>備註<input name="note"/></label><button className="primaryButton wide">＋ 新增實際出勤</button></form><div className="list">{dayWorks.length===0?<p className="muted">這天尚無教練出勤。</p>:dayWorks.map(w=>{const count=estimateCount(w),pay=calcPay(w);return <article key={w.id}><div><b>{profileMap.get(w.coach_user_id)?.display_name||'教練'}｜{String(w.start_time).slice(0,5)}–{String(w.end_time).slice(0,5)}</b><small>{w.student_count==null?`系統估算 ${count} 人`:`手動 ${count} 人`}｜本段約 ${Math.round(pay).toLocaleString()}</small></div><form action={deleteCoachAttendance}><input type="hidden" name="id" value={w.id}/><button className="dangerButton">刪除</button></form></article>})}</div></section>

    <section className="card"><div className="sectionTitle"><div><span>04</span><h2>本月教練薪酬</h2></div><strong>{month}</strong></div><div className="salaryGrid">{coaches.map(c=><article key={c.id}><b>{c.display_name||c.email}</b><strong>${Math.round(coachTotals.get(c.id)??0).toLocaleString()}</strong><span>{workList.filter(w=>w.coach_user_id===c.id).length} 個出勤時段</span></article>)}</div><div className="summary"><span>教練薪酬合計 <b>${Math.round(salaryTotal).toLocaleString()}</b></span></div></section>

    <section className="card"><div className="sectionTitle"><div><span>05</span><h2>本月營收／其他支出</h2></div></div><form method="get" className="inline"><input type="month" name="month" defaultValue={month}/><button className="secondaryButton">切換月份</button></form><form action={addFinanceItem} className="grid"><input type="hidden" name="record_month" value={month}/><label>類型<select name="item_type"><option value="income">收入</option><option value="expense">支出</option></select></label><label>項目<input name="category" required placeholder="月費／器材／場租…"/></label><label>金額<input type="number" name="amount" min="0" required/></label><label>說明<input name="description"/></label><button className="primaryButton wide">＋ 新增收支</button></form><div className="list">{(finance??[]).map(x=><article key={x.id}><div><b>{x.item_type==='income'?'收入':'支出'}｜{x.category}</b><small>{x.description||''}</small></div><strong>${Number(x.amount).toLocaleString()}</strong><form action={deleteFinanceItem}><input type="hidden" name="id" value={x.id}/><button className="dangerButton">刪除</button></form></article>)}</div></section>

    <section className="card"><div className="sectionTitle"><div><span>06</span><h2>本月財務月結</h2></div><strong>{net>=0?'結餘':'赤字'}</strong></div><div className="financeSummary"><article><span>營收</span><strong>${Math.round(income).toLocaleString()}</strong></article><article><span>教練薪酬</span><strong>-${Math.round(salaryTotal).toLocaleString()}</strong></article><article><span>冷氣費</span><strong>-${Math.round(airconCost).toLocaleString()}</strong></article><article><span>其他支出</span><strong>-${Math.round(manualExpense).toLocaleString()}</strong></article><article className="net"><span>本月結餘</span><strong>${Math.round(net).toLocaleString()}</strong></article></div><div className="notice" style={{marginTop:12}}>目前營收／其他支出可手動輸入；冷氣費與教練薪酬已會自動帶入。後續月費系統完成後，營收也可以自動抓。</div></section>
    <style>{`.coachRuleGrid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.ruleCard,.salaryGrid article,.financeSummary article{border:1px solid #e0e6eb;border-radius:15px;padding:14px;background:#fff}.ruleCard h3{margin:0 0 10px}.ruleCard label,.grid label{font-size:12px;font-weight:800;color:#637083}.ruleCard input,.ruleCard select,.grid input,.grid select,.inline input{display:block;width:100%;margin-top:5px;padding:9px 10px;border:1px solid #dce2e8;border-radius:10px;background:#fff;font:inherit}.miniGrid{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin:8px 0}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:9px}.grid .wide{grid-column:1/-1}.list{display:grid;gap:8px;margin-top:12px}.list article{display:grid;grid-template-columns:1fr auto auto;gap:10px;align-items:center;border:1px solid #e1e6eb;border-radius:13px;padding:11px;background:#fff}.list small{display:block;color:#748191;margin-top:3px}.inline{display:flex;gap:9px;align-items:end;margin:10px 0}.inline form{display:flex;gap:8px;align-items:end}.salaryGrid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.salaryGrid article{display:flex;flex-direction:column;gap:4px}.salaryGrid strong{font-size:24px}.salaryGrid span{color:#748191}.summary{margin-top:12px;padding:14px;border-radius:14px;background:var(--theme-soft,#f3f6f8)}.summary b{font-size:22px}.financeSummary{display:grid;grid-template-columns:repeat(5,1fr);gap:9px}.financeSummary article{display:flex;flex-direction:column;gap:5px}.financeSummary strong{font-size:20px}.financeSummary .net{background:var(--theme-soft,#eef7f4)}@media(max-width:900px){.coachRuleGrid{grid-template-columns:1fr}.grid{grid-template-columns:1fr 1fr}.salaryGrid,.financeSummary{grid-template-columns:1fr 1fr}}@media(max-width:560px){.miniGrid,.grid,.salaryGrid,.financeSummary{grid-template-columns:1fr}.grid .wide{grid-column:auto}.inline,.inline form{align-items:stretch;flex-direction:column}.list article{grid-template-columns:1fr}.list button{width:100%}}`}</style>
  </main>
}
