import Link from 'next/link';
import { redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';
import { addCoachAttendance,addCoachScheduleFromAttendanceTemplate,addCoachScheduleTemplate,addFinanceItem,addStaffMember,applyCoachTemplatesToDate,applyCoachTemplatesToMonth,archiveStaffMember,deleteCoachAttendance,deleteCoachScheduleTemplate,deleteFinanceItem,saveCoachPayRule,updateStaffMember } from './actions';

const WEEK=['一','二','三','四','五','六','日'];
const pad=(n:number)=>String(n).padStart(2,'0');
const nowParts=()=>{const d=new Date();return {date:`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`,month:`${d.getFullYear()}-${pad(d.getMonth()+1)}`}};
const tm=(t:string)=>{const [h,m]=String(t).slice(0,5).split(':').map(Number);return h*60+m};
type Staff={id:string;linked_user_id:string|null;display_name:string;role_type:string;phone:string|null;note:string|null;active:boolean};
type Rule={staff_id:string|null;coach_user_id:string|null;method:string;monthly_salary:number;base_hourly_rate:number;per_student_hour:number;note:string|null};
type Work={id:string;staff_id:string|null;coach_user_id:string|null;work_date:string;start_time:string;end_time:string;source:string;note:string|null};
type Att={attendance_date:string;start_time:string;end_time:string;attendee_count:number|null};

export default async function PayrollPage({searchParams}:{searchParams:Promise<{month?:string;date?:string;message?:string;error?:string;calculate?:string}>}){
  const q=await searchParams;const n=nowParts();const month=q.month||n.month;const date=q.date||n.date;const calculate=q.calculate==='1';const monthStart=`${month}-01`;const nx=new Date(Number(month.slice(0,4)),Number(month.slice(5,7)),1);const nextMonth=`${nx.getFullYear()}-${pad(nx.getMonth()+1)}-01`;
  const supabase=await createClient();const {data:claims}=await supabase.auth.getClaims();if(!claims?.claims?.sub)redirect('/login');const {data:teamId}=await supabase.rpc('current_team_id');if(!teamId)redirect('/more');
  const [{data:staff},{data:rules},{data:templates},{data:dayWorks},{data:finance},{data:meter},{data:studentTemplates},monthlyWorksResult,monthlyAttResult]=await Promise.all([
    supabase.from('staff_members').select('id,linked_user_id,display_name,role_type,phone,note,active').eq('team_id',teamId).order('active',{ascending:false}).order('display_name'),
    supabase.from('coach_pay_rules').select('staff_id,coach_user_id,method,monthly_salary,base_hourly_rate,per_student_hour,note').eq('team_id',teamId),
    supabase.from('coach_schedule_templates').select('id,staff_id,coach_user_id,weekday,start_time,end_time,note').eq('team_id',teamId).eq('active',true).order('weekday').order('start_time'),
    supabase.from('coach_attendance_segments').select('id,staff_id,coach_user_id,work_date,start_time,end_time,source,note').eq('team_id',teamId).eq('work_date',date).order('start_time'),
    supabase.from('finance_items').select('id,record_month,item_type,category,description,amount').eq('team_id',teamId).eq('record_month',monthStart).order('created_at'),
    supabase.from('aircon_meter_records').select('opening_reading,closing_reading,rate_per_unit,fixed_fee').eq('team_id',teamId).eq('record_month',monthStart).maybeSingle(),
    supabase.from('attendance_templates').select('id,weekday,start_time,end_time,default_count,note').eq('team_id',teamId).eq('mode','count').eq('active',true).order('weekday').order('start_time'),
    calculate?supabase.from('coach_attendance_segments').select('id,staff_id,coach_user_id,work_date,start_time,end_time,source,note').eq('team_id',teamId).gte('work_date',monthStart).lt('work_date',nextMonth):Promise.resolve({data:[]} as any),
    calculate?supabase.from('daily_attendance_segments').select('attendance_date,start_time,end_time,attendee_count').eq('team_id',teamId).eq('mode','count').gte('attendance_date',monthStart).lt('attendance_date',nextMonth):Promise.resolve({data:[]} as any),
  ]);
  const staffList=(staff??[]) as Staff[],activeStaff=staffList.filter(s=>s.active),staffMap=new Map(staffList.map(s=>[s.id,s]));
  const ruleMap=new Map<string,Rule>();for(const r of (rules??[]) as Rule[]){const k=r.staff_id||r.coach_user_id;if(k)ruleMap.set(k,r);}
  const keyFor=(w:Work)=>w.staff_id||w.coach_user_id||'';const nameFor=(w:Work)=>w.staff_id?staffMap.get(w.staff_id)?.display_name||'人員':'教練／人員';
  const totals=new Map<string,number>();let salaryTotal=0;
  if(calculate){
    const works=(monthlyWorksResult.data??[]) as Work[],att=(monthlyAttResult.data??[]) as Att[];const byDate=new Map<string,Att[]>();for(const a of att){const list=byDate.get(a.attendance_date)??[];list.push(a);byDate.set(a.attendance_date,list);}
    for(const s of activeStaff){const r=ruleMap.get(s.id);if(r?.method==='fixed_monthly'){const pay=Number(r.monthly_salary??0);totals.set(s.id,pay);salaryTotal+=pay;}}
    const countAt=(date:string,a:number,b:number)=>{let total=0;for(const x of byDate.get(date)??[]){const xs=tm(x.start_time),xe=tm(x.end_time);if(Math.min(b,xe)<=Math.max(a,xs))continue;total+=Number(x.attendee_count??0);}return total;};
    for(const w of works){const k=keyFor(w),r=ruleMap.get(k);if(!k||!r||r.method!=='weighted_students')continue;const start=tm(w.start_time),end=tm(w.end_time);const pts=new Set<number>([start,end]);for(const a of byDate.get(w.work_date)??[]){const s=Math.max(start,tm(a.start_time)),e=Math.min(end,tm(a.end_time));if(e>s){pts.add(s);pts.add(e);}}const p=[...pts].sort((a,b)=>a-b);let pay=0;for(let i=0;i<p.length-1;i++){const a=p[i],b=p[i+1];if(b<=a)continue;const count=countAt(w.work_date,a,b);const hourly=Number(r.base_hourly_rate??0)+Number(r.per_student_hour??0)*count;pay+=(b-a)/60*hourly;}totals.set(k,(totals.get(k)??0)+pay);salaryTotal+=pay;}
  }
  const income=(finance??[]).filter(x=>x.item_type==='income').reduce((a,x)=>a+Number(x.amount),0),manualExpense=(finance??[]).filter(x=>x.item_type==='expense').reduce((a,x)=>a+Number(x.amount),0),airconCost=meter?(Number(meter.closing_reading)-Number(meter.opening_reading))*Number(meter.rate_per_unit)+Number(meter.fixed_fee):0,net=income-manualExpense-salaryTotal-airconCost;

  return <main className="shell">
    <section className="hero compactHero"><div className="eyebrow">PAYROLL V4 · COUNT BASED</div><h1>教練薪酬與月結</h1><p>學生端只讀每日「時段＋人數」，不讀個別學生。計薪只保留固定月薪，或依教練出勤時段與當下學生人數加權。</p><div className="topNav"><Link href="/attendance-settings">學生出勤</Link><Link href="/aircon">冷氣費</Link><Link href="/more">更多</Link></div></section>{q.message?<div className="notice successNotice">{q.message}</div>:null}{q.error?<div className="notice errorNotice">{q.error}</div>:null}

    <section className="card"><div className="sectionTitle"><div><span>01</span><h2>教練／工作人員</h2></div><strong>{activeStaff.length} 人</strong></div><form action={addStaffMember} className="grid"><label>姓名<input name="display_name" required/></label><label>類型<select name="role_type"><option value="coach">教練</option><option value="assistant">助教</option><option value="admin">行政</option><option value="other">其他</option></select></label><label>電話<input name="phone"/></label><label>備註<input name="note"/></label><button className="primaryButton wide">＋ 新增人員</button></form><div className="list">{staffList.map(s=><article key={s.id}><form action={updateStaffMember} className="inline"><input type="hidden" name="id" value={s.id}/><input name="display_name" defaultValue={s.display_name}/><select name="role_type" defaultValue={s.role_type}><option value="coach">教練</option><option value="assistant">助教</option><option value="admin">行政</option><option value="other">其他</option></select><input name="phone" defaultValue={s.phone??''} placeholder="電話"/><input name="note" defaultValue={s.note??''} placeholder="備註"/><button className="secondaryButton">儲存</button></form>{s.active?<form action={archiveStaffMember}><input type="hidden" name="id" value={s.id}/><button className="dangerButton">停用</button></form>:<span className="muted">已停用</span>}</article>)}</div></section>

    <section className="card"><div className="sectionTitle"><div><span>02</span><h2>計薪規則</h2></div><strong>只留 2 種</strong></div><div className="notice">加權模式公式：每一小段工時 ×（基本時薪＋每位學生／小時加成 × 該時段學生人數）。學生人數直接取「學生出勤」的每日時段資料。</div><div className="ruleGrid">{activeStaff.map(s=>{const r=ruleMap.get(s.id);const method=['fixed_monthly','weighted_students'].includes(r?.method??'')?r?.method:'weighted_students';return <form action={saveCoachPayRule} key={s.id} className="rule"><input type="hidden" name="staff_id" value={s.id}/><b>{s.display_name}</b><label>計薪方式<select name="method" defaultValue={method}><option value="fixed_monthly">固定月薪</option><option value="weighted_students">教練出勤 × 學生人數加權</option></select></label><label>固定月薪<input type="number" name="monthly_salary" min="0" defaultValue={r?.monthly_salary??0}/></label><label>加權基本時薪<input type="number" name="base_hourly_rate" min="0" defaultValue={r?.base_hourly_rate??0}/></label><label>每位學生／小時加成<input type="number" name="per_student_hour" min="0" step="0.01" defaultValue={r?.per_student_hour??0}/></label><input name="note" defaultValue={r?.note??''} placeholder="備註"/><button className="secondaryButton">儲存規則</button></form>})}</div></section>

    <section className="card"><div className="sectionTitle"><div><span>03</span><h2>固定每週教練班表</h2></div></div><form action={addCoachScheduleFromAttendanceTemplate} className="inline"><select name="staff_id">{activeStaff.map(s=><option key={s.id} value={s.id}>{s.display_name}</option>)}</select><select name="attendance_template_id">{(studentTemplates??[]).map((t:any)=><option key={t.id} value={t.id}>週{WEEK[Number(t.weekday)-1]}｜{String(t.start_time).slice(0,5)}–{String(t.end_time).slice(0,5)}｜學生 {t.default_count??0} 人</option>)}</select><button className="primaryButton">由學生時段建立</button></form><details><summary className="secondaryButton">＋ 手動新增班表</summary><form action={addCoachScheduleTemplate} className="grid"><label>人員<select name="staff_id">{activeStaff.map(s=><option key={s.id} value={s.id}>{s.display_name}</option>)}</select></label><label>星期<select name="weekday">{WEEK.map((w,i)=><option key={w} value={i+1}>星期{w}</option>)}</select></label><label>開始<input type="time" name="start_time" required/></label><label>結束<input type="time" name="end_time" required/></label><label className="wide">備註<input name="note"/></label><button className="primaryButton wide">新增班表</button></form></details><div className="list">{(templates??[]).map((t:any)=><article key={t.id}><div><b>{t.staff_id?staffMap.get(t.staff_id)?.display_name:'人員'}｜週{WEEK[Number(t.weekday)-1]} {String(t.start_time).slice(0,5)}–{String(t.end_time).slice(0,5)}</b>{t.note?<small>{t.note}</small>:null}</div><form action={deleteCoachScheduleTemplate}><input type="hidden" name="id" value={t.id}/><button className="dangerButton">刪除</button></form></article>)}</div></section>

    <section className="card"><div className="sectionTitle"><div><span>04</span><h2>套用教練班表</h2></div><strong>{month}</strong></div><div className="inline"><form action={applyCoachTemplatesToMonth} className="inline"><input type="month" name="month" defaultValue={month}/><button className="primaryButton">套用整月</button></form><form action={applyCoachTemplatesToDate} className="inline"><input type="date" name="work_date" defaultValue={date}/><button className="secondaryButton">只套這一天</button></form></div></section>

    <section className="card"><div className="sectionTitle"><div><span>05</span><h2>某一天教練實際出勤</h2></div><strong>{date}</strong></div><form method="get" className="inline"><input type="date" name="date" defaultValue={date}/><input type="hidden" name="month" value={month}/><button className="secondaryButton">查看日期</button></form><form action={addCoachAttendance} className="grid"><label>人員<select name="staff_id">{activeStaff.map(s=><option key={s.id} value={s.id}>{s.display_name}</option>)}</select></label><label>日期<input type="date" name="work_date" defaultValue={date}/></label><label>開始<input type="time" name="start_time" required/></label><label>結束<input type="time" name="end_time" required/></label><label className="wide">備註<input name="note"/></label><button className="primaryButton wide">＋ 新增實際出勤</button></form><div className="list">{(dayWorks??[]).length===0?<p className="muted">這天還沒有教練出勤紀錄。</p>:(dayWorks??[]).map((w:any)=><article key={w.id}><div><b>{nameFor(w)}｜{String(w.start_time).slice(0,5)}–{String(w.end_time).slice(0,5)}</b><small>{w.source==='template'?'固定班表':'手動'}{w.note?`｜${w.note}`:''}</small></div><form action={deleteCoachAttendance}><input type="hidden" name="id" value={w.id}/><input type="hidden" name="work_date" value={date}/><button className="dangerButton">刪除</button></form></article>)}</div></section>

    <section className="card"><div className="sectionTitle"><div><span>06</span><h2>本月薪酬試算</h2></div><strong>{month}</strong></div>{!calculate?<><div className="notice">平常開頁不做整月計算；需要看薪酬時才讀取整月教練出勤與學生「時段人數」。</div><Link className="primaryButton calc" href={`/payroll?month=${month}&date=${date}&calculate=1`}>計算本月薪酬</Link></>:<div className="salaryGrid">{activeStaff.map(s=><article key={s.id}><b>{s.display_name}</b><strong>${Math.round(totals.get(s.id)??0).toLocaleString()}</strong><span>{ruleMap.get(s.id)?.method==='fixed_monthly'?'固定月薪':'出勤 × 學生人數加權'}</span></article>)}</div>}</section>

    <section className="card"><div className="sectionTitle"><div><span>07</span><h2>其他收支與月結</h2></div><strong>{month}</strong></div><form action={addFinanceItem} className="grid"><input type="hidden" name="record_month" value={month}/><label>類型<select name="item_type"><option value="income">收入</option><option value="expense">支出</option></select></label><label>分類<input name="category" required/></label><label>說明<input name="description"/></label><label>金額<input type="number" name="amount" min="0" required/></label><button className="primaryButton wide">＋ 新增收支</button></form><div className="list">{(finance??[]).map((x:any)=><article key={x.id}><div><b>{x.item_type==='income'?'收入':'支出'}｜{x.category}｜${Number(x.amount).toLocaleString()}</b><small>{x.description??''}</small></div><form action={deleteFinanceItem}><input type="hidden" name="id" value={x.id}/><input type="hidden" name="month" value={month}/><button className="dangerButton">刪除</button></form></article>)}</div>{calculate?<div className="summary">收入 ${Math.round(income).toLocaleString()}｜其他支出 ${Math.round(manualExpense).toLocaleString()}｜教練薪酬 ${Math.round(salaryTotal).toLocaleString()}｜冷氣 ${Math.round(airconCost).toLocaleString()}｜淨額 <b>${Math.round(net).toLocaleString()}</b></div>:null}</section>
    <style>{`.inline{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin:10px 0}.inline input,.inline select,.grid input,.grid select,.rule input,.rule select{padding:9px;border:1px solid #dce2e8;border-radius:10px;background:#fff}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.grid label,.rule label{font-size:12px;font-weight:800;color:#637083}.grid input,.grid select,.rule input,.rule select{display:block;width:100%;margin-top:4px}.wide{grid-column:1/-1}.list{display:grid;gap:7px;margin-top:10px}.list article{display:grid;grid-template-columns:1fr auto;gap:10px;align-items:center;padding:10px;border:1px solid #e1e6eb;border-radius:13px;background:#fff}.list small{display:block;color:#748191}.ruleGrid{display:grid;grid-template-columns:repeat(2,1fr);gap:9px}.rule{display:grid;gap:7px;padding:12px;border:1px solid #e1e6eb;border-radius:14px;background:#fff}.salaryGrid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.salaryGrid article{padding:12px;border:1px solid #e1e6eb;border-radius:13px;background:#fff;display:flex;flex-direction:column}.salaryGrid strong{font-size:20px}.salaryGrid span{color:#748191}.calc{display:inline-block;text-decoration:none;margin-top:10px}.summary{margin-top:12px;padding:14px;border-radius:14px;background:var(--theme-soft,#f4f7fa)}summary{cursor:pointer;margin:10px 0}@media(max-width:900px){.grid,.salaryGrid{grid-template-columns:1fr 1fr}.ruleGrid{grid-template-columns:1fr}}@media(max-width:560px){.inline{align-items:stretch;flex-direction:column}.grid,.salaryGrid{grid-template-columns:1fr}.wide{grid-column:auto}.list article{grid-template-columns:1fr}}`}</style>
  </main>;
}
